version: "3"

services:
  nodeapp:
    image: nodeapp:v0.1
    environment:
      - NODE_ENV=production
    expose:
      - "8080"
  
  proxy:
    image: nginx:1.21-alpine
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443